# Generated by Django 5.2.15 on 2026-06-12 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verb', models.CharField(choices=[('follow', 'Followed you'), ('like_theme', 'Liked your theme'), ('like_reply', 'Liked your reply'), ('reply', 'Replied to your theme'), ('repost', 'Reposted your theme')], max_length=16)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
