# Generated by Django 5.2.15 on 2026-06-19 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_search_event'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='searchevent',
            new_name='users_searc_tab_8c98bb_idx',
            old_name='users_searc_tab_6a0f0d_idx',
        ),
    ]
