# Generated by Django 5.2.15 on 2026-06-29 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_users_searc_tab_6a0f0d_idx_users_searc_tab_8c98bb_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('ru', 'Russian'), ('uz', 'Uzbek')], default='en', max_length=5),
        ),
    ]
