# Generated by Django 5.2.15 on 2026-06-12 20:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('threads', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reply',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='threads.reply'),
        ),
        migrations.AddField(
            model_name='replyimage',
            name='reply',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='threads.reply'),
        ),
        migrations.AddField(
            model_name='replylike',
            name='reply',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='threads.reply'),
        ),
        migrations.AddField(
            model_name='replylike',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reply_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='replyrepost',
            name='reply',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reposts', to='threads.reply'),
        ),
        migrations.AddField(
            model_name='replyrepost',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reply_reposts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='theme',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='themes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='theme',
            name='hashtags',
            field=models.ManyToManyField(blank=True, related_name='themes', to='threads.hashtag'),
        ),
        migrations.AddField(
            model_name='reply',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='threads.theme'),
        ),
        migrations.AddField(
            model_name='themeimage',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='threads.theme'),
        ),
        migrations.AddField(
            model_name='themelike',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='threads.theme'),
        ),
        migrations.AddField(
            model_name='themelike',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theme_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='themerepost',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reposts', to='threads.theme'),
        ),
        migrations.AddField(
            model_name='themerepost',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theme_reposts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='replylike',
            unique_together={('reply', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='replyrepost',
            unique_together={('reply', 'user')},
        ),
        migrations.AddIndex(
            model_name='theme',
            index=models.Index(fields=['-created_at'], name='threads_the_created_b808f2_idx'),
        ),
        migrations.AddIndex(
            model_name='theme',
            index=models.Index(fields=['author', '-created_at'], name='threads_the_author__8f724c_idx'),
        ),
        migrations.AddIndex(
            model_name='reply',
            index=models.Index(fields=['theme', 'created_at'], name='threads_rep_theme_i_f798b0_idx'),
        ),
        migrations.AddIndex(
            model_name='reply',
            index=models.Index(fields=['parent', 'created_at'], name='threads_rep_parent__e6d36b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='themelike',
            unique_together={('theme', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='themerepost',
            unique_together={('theme', 'user')},
        ),
    ]
