# Generated by Django 5.2.15 on 2026-06-15 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0004_recalc_theme_top_level_replies_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reply',
            options={'ordering': ('-created_at',), 'verbose_name_plural': 'replies'},
        ),
    ]
