# Generated by Django 5.2.15 on 2026-06-24 00:38

import apps.threads.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0005_alter_reply_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReplyMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=8)),
                ('image', models.ImageField(blank=True, null=True, upload_to='replies/%Y/%m/%d/')),
                ('image_thumbnail', models.ImageField(blank=True, null=True, upload_to='replies/')),
                ('image_medium', models.ImageField(blank=True, null=True, upload_to='replies/')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='replies/video/%Y/%m/%d/')),
                ('poster', models.ImageField(blank=True, null=True, upload_to='replies/poster/%Y/%m/%d/')),
                ('poster_thumbnail', models.ImageField(blank=True, null=True, upload_to='replies/poster/')),
                ('poster_medium', models.ImageField(blank=True, null=True, upload_to='replies/poster/')),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('mime', models.CharField(blank=True, default='', max_length=64)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('sort_order', models.PositiveSmallIntegerField(db_index=True, default=0)),
                ('orientation_kind', models.CharField(choices=[('landscape', 'Landscape'), ('portrait', 'Portrait'), ('wide', 'Ultra-wide'), ('square', 'Square')], default='landscape', max_length=16)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('reply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='threads.reply')),
            ],
            options={
                'ordering': ('sort_order', 'pk'),
            },
            bases=(apps.threads.models._MediaUrlMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ThemeMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=8)),
                ('image', models.ImageField(blank=True, null=True, upload_to='themes/%Y/%m/%d/')),
                ('image_thumbnail', models.ImageField(blank=True, null=True, upload_to='themes/')),
                ('image_medium', models.ImageField(blank=True, null=True, upload_to='themes/')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='themes/video/%Y/%m/%d/')),
                ('poster', models.ImageField(blank=True, null=True, upload_to='themes/poster/%Y/%m/%d/')),
                ('poster_thumbnail', models.ImageField(blank=True, null=True, upload_to='themes/poster/')),
                ('poster_medium', models.ImageField(blank=True, null=True, upload_to='themes/poster/')),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('mime', models.CharField(blank=True, default='', max_length=64)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('sort_order', models.PositiveSmallIntegerField(db_index=True, default=0)),
                ('orientation_kind', models.CharField(choices=[('landscape', 'Landscape'), ('portrait', 'Portrait'), ('wide', 'Ultra-wide'), ('square', 'Square')], default='landscape', max_length=16)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='threads.theme')),
            ],
            options={
                'ordering': ('sort_order', 'pk'),
            },
            bases=(apps.threads.models._MediaUrlMixin, models.Model),
        ),
    ]
