# Generated by Django 5.2.15 on 2026-06-24 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0007_migrate_images_to_media'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='themeimage',
            name='theme',
        ),
        migrations.DeleteModel(
            name='ReplyImage',
        ),
        migrations.DeleteModel(
            name='ThemeImage',
        ),
    ]
